const ActionType = {
    LOAD_POSTS: `LOAD_POSTS`,
    LOAD_SORTING_POSTS: `LOAD_SORTING_POSTS`,
    LOAD_USER: `LOAD_USER`,
    CHANGE_LOAD_STATUS: `CHANGE_LOAD_STATUS`,
    CHANGE_POST_ID: `CHANGE_POST_ID`,
    CHANGE_POST_CATEGORY: `CHANGE_POST_CATEGORY`,
};

export default ActionType;
